services:
  api:
    build:
      context: .
      dockerfile: ./backend/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./models/data:/app/data
    environment:
      - PYTHONPATH=/app/models:/app
      - MODEL_PATH=/app/models
      - DATABASE_URL=sqlite:///./eyevsai_dev.db
      - SECRET_KEY=eyevsai-dev-secret-key-not-for-production-use-only-local-testing-12345
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/game
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  redis_data: